### ISSUE TITLE
implement php service template

### ISSUE THREAD

**Issue by Kravalg** [VilnaCRM-Org/php-service-template#2]
As a developer, I need to be able easily to create and set up new microservice for the VilnaCRM project

### Technical requirements

- [x] PHP 8.1
- [x] API platform 3

### Tasks

- [x] create the repository template for PHP-based microservices
- [x] set up docker for service
- [x] set up CI checks using Github actions (psalm, phpcs, [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and etc.)
- [x] configure conventional commits git hook
- [x] write for all repositories CONTRIBUTE.md and README.md
- [x] check that swagger documentation looks good
- [x] add [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [x] cover the code with auto-tests

### Backend CI checks

- [x] psalm (plugins: phpunit, symfony, doctrine, strict-types)
- [x] phpcsfixer
- [x] composer validate
- [x] conventional commits
- [x] symfony check:security
- [x] symfony check:requirements
- [x] phpunit
- [x] behat
- [x] symfony e2e tests
- [x] GitHub actions CI
- [x] php insights
- [x] phpinsights badger
- [x] PHP Copy Paste Detector
- [ ] ASST
- [x] php-conventional-changelog
- [x] codecov
- [x] Artillery load testing
- [x] CodeScene
- [ ] OWASP ZAP
- [ ] SonarQube
- [ ] Snyk
- [ ] Trivy
- [ ] [docker-bench-security](https://github.com/docker/docker-bench-security)
- [ ] [secret-diver](https://github.com/cider-rnd/secret-diver)
- [ ] [check for API backward compatibility](https://github.com/marketplace/actions/openapi-diff)

### Acceptance criteria

- [ ] the PHP service template implemented and works as GitHub public template
- [ ] all tests passed
